const countries = [
  {
    flag: "af.png",
    name: "Afghanistan",
    alpha2Code: "AF",
    callingCode: "93",
  },
  {
    flag: "ax.png",
    name: "Åland Islands",
    alpha2Code: "AX",
    callingCode: "358",
  },
  {
    flag: "al.png",
    name: "Albania",
    alpha2Code: "AL",
    callingCode: "355",
  },
  {
    flag: "dz.png",
    name: "Algeria",
    alpha2Code: "DZ",
    callingCode: "213",
  },
  {
    flag: "as.png",
    name: "American Samoa",
    alpha2Code: "AS",
    callingCode: "1684",
  },
  {
    flag: "ad.png",
    name: "Andorra",
    alpha2Code: "AD",
    callingCode: "376",
  },
  {
    flag: "ao.png",
    name: "Angola",
    alpha2Code: "AO",
    callingCode: "244",
  },
  {
    flag: "ai.png",
    name: "Anguilla",
    alpha2Code: "AI",
    callingCode: "1264",
  },
  {
    flag: "aq.png",
    name: "Antarctica",
    alpha2Code: "AQ",
    callingCode: "672",
  },
  {
    flag: "ag.png",
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    callingCode: "1268",
  },
  {
    flag: "ar.png",
    name: "Argentina",
    alpha2Code: "AR",
    callingCode: "54",
  },
  {
    flag: "am.png",
    name: "Armenia",
    alpha2Code: "AM",
    callingCode: "374",
  },
  {
    flag: "aw.png",
    name: "Aruba",
    alpha2Code: "AW",
    callingCode: "297",
  },
  {
    flag: "au.png",
    name: "Australia",
    alpha2Code: "AU",
    callingCode: "61",
  },
  {
    flag: "at.png",
    name: "Austria",
    alpha2Code: "AT",
    callingCode: "43",
  },
  {
    flag: "az.png",
    name: "Azerbaijan",
    alpha2Code: "AZ",
    callingCode: "994",
  },
  {
    flag: "bs.png",
    name: "Bahamas",
    alpha2Code: "BS",
    callingCode: "1242",
  },
  {
    flag: "bh.png",
    name: "Bahrain",
    alpha2Code: "BH",
    callingCode: "973",
  },
  {
    flag: "bd.png",
    name: "Bangladesh",
    alpha2Code: "BD",
    callingCode: "880",
  },
  {
    flag: "bb.png",
    name: "Barbados",
    alpha2Code: "BB",
    callingCode: "1246",
  },
  {
    flag: "by.png",
    name: "Belarus",
    alpha2Code: "BY",
    callingCode: "375",
  },
  {
    flag: "be.png",
    name: "Belgium",
    alpha2Code: "BE",
    callingCode: "32",
  },
  {
    flag: "bz.png",
    name: "Belize",
    alpha2Code: "BZ",
    callingCode: "501",
  },
  {
    flag: "bj.png",
    name: "Benin",
    alpha2Code: "BJ",
    callingCode: "229",
  },
  {
    flag: "bm.png",
    name: "Bermuda",
    alpha2Code: "BM",
    callingCode: "1441",
  },
  {
    flag: "bt.png",
    name: "Bhutan",
    alpha2Code: "BT",
    callingCode: "975",
  },
  {
    flag: "bo.png",
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    callingCode: "591",
  },
  {
    flag: "bq.png",
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    callingCode: "5997",
  },
  {
    flag: "ba.png",
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    callingCode: "387",
  },
  {
    flag: "bw.png",
    name: "Botswana",
    alpha2Code: "BW",
    callingCode: "267",
  },
  {
    flag: "br.png",
    name: "Brazil",
    alpha2Code: "BR",
    callingCode: "55",
  },
  {
    flag: "io.png",
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    callingCode: "246",
  },
  {
    flag: "vg.png",
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    callingCode: "1284",
  },
  {
    flag: "vi.png",
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    callingCode: "1 340",
  },
  {
    flag: "bn.png",
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    callingCode: "673",
  },
  {
    flag: "bg.png",
    name: "Bulgaria",
    alpha2Code: "BG",
    callingCode: "359",
  },
  {
    flag: "bf.png",
    name: "Burkina Faso",
    alpha2Code: "BF",
    callingCode: "226",
  },
  {
    flag: "bi.png",
    name: "Burundi",
    alpha2Code: "BI",
    callingCode: "257",
  },
  {
    flag: "kh.png",
    name: "Cambodia",
    alpha2Code: "KH",
    callingCode: "855",
  },
  {
    flag: "cm.png",
    name: "Cameroon",
    alpha2Code: "CM",
    callingCode: "237",
  },
  {
    flag: "ca.png",
    name: "Canada",
    alpha2Code: "CA",
    callingCode: "1",
  },
  {
    flag: "cv.png",
    name: "Cabo Verde",
    alpha2Code: "CV",
    callingCode: "238",
  },
  {
    flag: "ky.png",
    name: "Cayman Islands",
    alpha2Code: "KY",
    callingCode: "1345",
  },
  {
    flag: "cf.png",
    name: "Central African Republic",
    alpha2Code: "CF",
    callingCode: "236",
  },
  {
    flag: "td.png",
    name: "Chad",
    alpha2Code: "TD",
    callingCode: "235",
  },
  {
    flag: "cl.png",
    name: "Chile",
    alpha2Code: "CL",
    callingCode: "56",
  },
  {
    flag: "cn.png",
    name: "China",
    alpha2Code: "CN",
    callingCode: "86",
  },
  {
    flag: "cx.png",
    name: "Christmas Island",
    alpha2Code: "CX",
    callingCode: "61",
  },
  {
    flag: "cc.png",
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    callingCode: "61",
  },
  {
    flag: "co.png",
    name: "Colombia",
    alpha2Code: "CO",
    callingCode: "57",
  },
  {
    flag: "km.png",
    name: "Comoros",
    alpha2Code: "KM",
    callingCode: "269",
  },
  {
    flag: "cg.png",
    name: "Congo",
    alpha2Code: "CG",
    callingCode: "242",
  },
  {
    flag: "cd.png",
    name: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    callingCode: "243",
  },
  {
    flag: "ck.png",
    name: "Cook Islands",
    alpha2Code: "CK",
    callingCode: "682",
  },
  {
    flag: "cr.png",
    name: "Costa Rica",
    alpha2Code: "CR",
    callingCode: "506",
  },
  {
    flag: "hr.png",
    name: "Croatia",
    alpha2Code: "HR",
    callingCode: "385",
  },
  {
    flag: "cu.png",
    name: "Cuba",
    alpha2Code: "CU",
    callingCode: "53",
  },
  {
    flag: "cw.png",
    name: "Curaçao",
    alpha2Code: "CW",
    callingCode: "599",
  },
  {
    flag: "cy.png",
    name: "Cyprus",
    alpha2Code: "CY",
    callingCode: "357",
  },
  {
    flag: "cz.png",
    name: "Czech Republic",
    alpha2Code: "CZ",
    callingCode: "420",
  },
  {
    flag: "dk.png",
    name: "Denmark",
    alpha2Code: "DK",
    callingCode: "45",
  },
  {
    flag: "dj.png",
    name: "Djibouti",
    alpha2Code: "DJ",
    callingCode: "253",
  },
  {
    flag: "dm.png",
    name: "Dominica",
    alpha2Code: "DM",
    callingCode: "1767",
  },
  {
    flag: "do.png",
    name: "Dominican Republic",
    alpha2Code: "DO",
    callingCode: "1809",
  },
  {
    flag: "ec.png",
    name: "Ecuador",
    alpha2Code: "EC",
    callingCode: "593",
  },
  {
    flag: "eg.png",
    name: "Egypt",
    alpha2Code: "EG",
    callingCode: "20",
  },
  {
    flag: "sv.png",
    name: "El Salvador",
    alpha2Code: "SV",
    callingCode: "503",
  },
  {
    flag: "gq.png",
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    callingCode: "240",
  },
  {
    flag: "er.png",
    name: "Eritrea",
    alpha2Code: "ER",
    callingCode: "291",
  },
  {
    flag: "ee.png",
    name: "Estonia",
    alpha2Code: "EE",
    callingCode: "372",
  },
  {
    flag: "et.png",
    name: "Ethiopia",
    alpha2Code: "ET",
    callingCode: "251",
  },
  {
    flag: "fk.png",
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    callingCode: "500",
  },
  {
    flag: "fo.png",
    name: "Faroe Islands",
    alpha2Code: "FO",
    callingCode: "298",
  },
  {
    flag: "fj.png",
    name: "Fiji",
    alpha2Code: "FJ",
    callingCode: "679",
  },
  {
    flag: "fi.png",
    name: "Finland",
    alpha2Code: "FI",
    callingCode: "358",
  },
  {
    flag: "fr.png",
    name: "France",
    alpha2Code: "FR",
    callingCode: "33",
  },
  {
    flag: "gf.png",
    name: "French Guiana",
    alpha2Code: "GF",
    callingCode: "594",
  },
  {
    flag: "pf.png",
    name: "French Polynesia",
    alpha2Code: "PF",
    callingCode: "689",
  },
  {
    flag: "ga.png",
    name: "Gabon",
    alpha2Code: "GA",
    callingCode: "241",
  },
  {
    flag: "gm.png",
    name: "Gambia",
    alpha2Code: "GM",
    callingCode: "220",
  },
  {
    flag: "ge.png",
    name: "Georgia",
    alpha2Code: "GE",
    callingCode: "995",
  },
  {
    flag: "de.png",
    name: "Germany",
    alpha2Code: "DE",
    callingCode: "49",
  },
  {
    flag: "gh.png",
    name: "Ghana",
    alpha2Code: "GH",
    callingCode: "233",
  },
  {
    flag: "gi.png",
    name: "Gibraltar",
    alpha2Code: "GI",
    callingCode: "350",
  },
  {
    flag: "gr.png",
    name: "Greece",
    alpha2Code: "GR",
    callingCode: "30",
  },
  {
    flag: "gl.png",
    name: "Greenland",
    alpha2Code: "GL",
    callingCode: "299",
  },
  {
    flag: "gd.png",
    name: "Grenada",
    alpha2Code: "GD",
    callingCode: "1473",
  },
  {
    flag: "gp.png",
    name: "Guadeloupe",
    alpha2Code: "GP",
    callingCode: "590",
  },
  {
    flag: "gu.png",
    name: "Guam",
    alpha2Code: "GU",
    callingCode: "1671",
  },
  {
    flag: "gt.png",
    name: "Guatemala",
    alpha2Code: "GT",
    callingCode: "502",
  },
  {
    flag: "gg.png",
    name: "Guernsey",
    alpha2Code: "GG",
    callingCode: "44",
  },
  {
    flag: "gn.png",
    name: "Guinea",
    alpha2Code: "GN",
    callingCode: "224",
  },
  {
    flag: "gw.png",
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    callingCode: "245",
  },
  {
    flag: "gy.png",
    name: "Guyana",
    alpha2Code: "GY",
    callingCode: "592",
  },
  {
    flag: "ht.png",
    name: "Haiti",
    alpha2Code: "HT",
    callingCode: "509",
  },
  {
    flag: "va.png",
    name: "Holy See",
    alpha2Code: "VA",
    callingCode: "379",
  },
  {
    flag: "hn.png",
    name: "Honduras",
    alpha2Code: "HN",
    callingCode: "504",
  },
  {
    flag: "hk.png",
    name: "Hong Kong",
    alpha2Code: "HK",
    callingCode: "852",
  },
  {
    flag: "hu.png",
    name: "Hungary",
    alpha2Code: "HU",
    callingCode: "36",
  },
  {
    flag: "is.png",
    name: "Iceland",
    alpha2Code: "IS",
    callingCode: "354",
  },
  {
    flag: "in.png",
    name: "India",
    alpha2Code: "IN",
    callingCode: "91",
  },
  {
    flag: "id.png",
    name: "Indonesia",
    alpha2Code: "ID",
    callingCode: "62",
  },
  {
    flag: "ci.png",
    name: "Côte d'Ivoire",
    alpha2Code: "CI",
    callingCode: "225",
  },
  {
    flag: "ir.png",
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    callingCode: "98",
  },
  {
    flag: "iq.png",
    name: "Iraq",
    alpha2Code: "IQ",
    callingCode: "964",
  },
  {
    flag: "ie.png",
    name: "Ireland",
    alpha2Code: "IE",
    callingCode: "353",
  },
  {
    flag: "im.png",
    name: "Isle of Man",
    alpha2Code: "IM",
    callingCode: "44",
  },
  {
    flag: "il.png",
    name: "Israel",
    alpha2Code: "IL",
    callingCode: "972",
  },
  {
    flag: "it.png",
    name: "Italy",
    alpha2Code: "IT",
    callingCode: "39",
  },
  {
    flag: "jm.png",
    name: "Jamaica",
    alpha2Code: "JM",
    callingCode: "1876",
  },
  {
    flag: "jp.png",
    name: "Japan",
    alpha2Code: "JP",
    callingCode: "81",
  },
  {
    flag: "je.png",
    name: "Jersey",
    alpha2Code: "JE",
    callingCode: "44",
  },
  {
    flag: "jo.png",
    name: "Jordan",
    alpha2Code: "JO",
    callingCode: "962",
  },
  {
    flag: "kz.png",
    name: "Kazakhstan",
    alpha2Code: "KZ",
    callingCode: "76",
  },
  {
    flag: "ke.png",
    name: "Kenya",
    alpha2Code: "KE",
    callingCode: "254",
  },
  {
    flag: "ki.png",
    name: "Kiribati",
    alpha2Code: "KI",
    callingCode: "686",
  },
  {
    flag: "kw.png",
    name: "Kuwait",
    alpha2Code: "KW",
    callingCode: "965",
  },
  {
    flag: "kg.png",
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    callingCode: "996",
  },
  {
    flag: "la.png",
    name: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    callingCode: "856",
  },
  {
    flag: "lv.png",
    name: "Latvia",
    alpha2Code: "LV",
    callingCode: "371",
  },
  {
    flag: "lb.png",
    name: "Lebanon",
    alpha2Code: "LB",
    callingCode: "961",
  },
  {
    flag: "ls.png",
    name: "Lesotho",
    alpha2Code: "LS",
    callingCode: "266",
  },
  {
    flag: "lr.png",
    name: "Liberia",
    alpha2Code: "LR",
    callingCode: "231",
  },
  {
    flag: "ly.png",
    name: "Libya",
    alpha2Code: "LY",
    callingCode: "218",
  },
  {
    flag: "li.png",
    name: "Liechtenstein",
    alpha2Code: "LI",
    callingCode: "423",
  },
  {
    flag: "lt.png",
    name: "Lithuania",
    alpha2Code: "LT",
    callingCode: "370",
  },
  {
    flag: "lu.png",
    name: "Luxembourg",
    alpha2Code: "LU",
    callingCode: "352",
  },
  {
    flag: "mo.png",
    name: "Macao",
    alpha2Code: "MO",
    callingCode: "853",
  },
  {
    flag: "mk.png",
    name: "Macedonia (the former Yugoslav Republic of)",
    alpha2Code: "MK",
    callingCode: "389",
  },
  {
    flag: "mg.png",
    name: "Madagascar",
    alpha2Code: "MG",
    callingCode: "261",
  },
  {
    flag: "mw.png",
    name: "Malawi",
    alpha2Code: "MW",
    callingCode: "265",
  },
  {
    flag: "my.png",
    name: "Malaysia",
    alpha2Code: "MY",
    callingCode: "60",
  },
  {
    flag: "mv.png",
    name: "Maldives",
    alpha2Code: "MV",
    callingCode: "960",
  },
  {
    flag: "ml.png",
    name: "Mali",
    alpha2Code: "ML",
    callingCode: "223",
  },
  {
    flag: "mt.png",
    name: "Malta",
    alpha2Code: "MT",
    callingCode: "356",
  },
  {
    flag: "mh.png",
    name: "Marshall Islands",
    alpha2Code: "MH",
    callingCode: "692",
  },
  {
    flag: "mq.png",
    name: "Martinique",
    alpha2Code: "MQ",
    callingCode: "596",
  },
  {
    flag: "mr.png",
    name: "Mauritania",
    alpha2Code: "MR",
    callingCode: "222",
  },
  {
    flag: "mu.png",
    name: "Mauritius",
    alpha2Code: "MU",
    callingCode: "230",
  },
  {
    flag: "yt.png",
    name: "Mayotte",
    alpha2Code: "YT",
    callingCode: "262",
  },
  {
    flag: "mx.png",
    name: "Mexico",
    alpha2Code: "MX",
    callingCode: "52",
  },
  {
    flag: "fm.png",
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    callingCode: "691",
  },
  {
    flag: "md.png",
    name: "Moldova (Republic of)",
    alpha2Code: "MD",
    callingCode: "373",
  },
  {
    flag: "mc.png",
    name: "Monaco",
    alpha2Code: "MC",
    callingCode: "377",
  },
  {
    flag: "mn.png",
    name: "Mongolia",
    alpha2Code: "MN",
    callingCode: "976",
  },
  {
    flag: "me.png",
    name: "Montenegro",
    alpha2Code: "ME",
    callingCode: "382",
  },
  {
    flag: "ms.png",
    name: "Montserrat",
    alpha2Code: "MS",
    callingCode: "1664",
  },
  {
    flag: "ma.png",
    name: "Morocco",
    alpha2Code: "MA",
    callingCode: "212",
  },
  {
    flag: "mz.png",
    name: "Mozambique",
    alpha2Code: "MZ",
    callingCode: "258",
  },
  {
    flag: "mm.png",
    name: "Myanmar",
    alpha2Code: "MM",
    callingCode: "95",
  },
  {
    flag: "na.png",
    name: "Namibia",
    alpha2Code: "NA",
    callingCode: "264",
  },
  {
    flag: "nr.png",
    name: "Nauru",
    alpha2Code: "NR",
    callingCode: "674",
  },
  {
    flag: "np.png",
    name: "Nepal",
    alpha2Code: "NP",
    callingCode: "977",
  },
  {
    flag: "nl.png",
    name: "Netherlands",
    alpha2Code: "NL",
    callingCode: "31",
  },
  {
    flag: "nc.png",
    name: "New Caledonia",
    alpha2Code: "NC",
    callingCode: "687",
  },
  {
    flag: "nz.png",
    name: "New Zealand",
    alpha2Code: "NZ",
    callingCode: "64",
  },
  {
    flag: "ni.png",
    name: "Nicaragua",
    alpha2Code: "NI",
    callingCode: "505",
  },
  {
    flag: "ne.png",
    name: "Niger",
    alpha2Code: "NE",
    callingCode: "227",
  },
  {
    flag: "ng.png",
    name: "Nigeria",
    alpha2Code: "NG",
    callingCode: "234",
  },
  {
    flag: "nu.png",
    name: "Niue",
    alpha2Code: "NU",
    callingCode: "683",
  },
  {
    flag: "nf.png",
    name: "Norfolk Island",
    alpha2Code: "NF",
    callingCode: "672",
  },
  {
    flag: "kp.png",
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    callingCode: "850",
  },
  {
    flag: "mp.png",
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    callingCode: "1670",
  },
  {
    flag: "no.png",
    name: "Norway",
    alpha2Code: "NO",
    callingCode: "47",
  },
  {
    flag: "om.png",
    name: "Oman",
    alpha2Code: "OM",
    callingCode: "968",
  },
  {
    flag: "pk.png",
    name: "Pakistan",
    alpha2Code: "PK",
    callingCode: "92",
  },
  {
    flag: "pw.png",
    name: "Palau",
    alpha2Code: "PW",
    callingCode: "680",
  },
  {
    flag: "ps.png",
    name: "Palestine, State of",
    alpha2Code: "PS",
    callingCode: "970",
  },
  {
    flag: "pa.png",
    name: "Panama",
    alpha2Code: "PA",
    callingCode: "507",
  },
  {
    flag: "pg.png",
    name: "Papua New Guinea",
    alpha2Code: "PG",
    callingCode: "675",
  },
  {
    flag: "py.png",
    name: "Paraguay",
    alpha2Code: "PY",
    callingCode: "595",
  },
  {
    flag: "pe.png",
    name: "Peru",
    alpha2Code: "PE",
    callingCode: "51",
  },
  {
    flag: "ph.png",
    name: "Philippines",
    alpha2Code: "PH",
    callingCode: "63",
  },
  {
    flag: "pn.png",
    name: "Pitcairn",
    alpha2Code: "PN",
    callingCode: "64",
  },
  {
    flag: "pl.png",
    name: "Poland",
    alpha2Code: "PL",
    callingCode: "48",
  },
  {
    flag: "pt.png",
    name: "Portugal",
    alpha2Code: "PT",
    callingCode: "351",
  },
  {
    flag: "pr.png",
    name: "Puerto Rico",
    alpha2Code: "PR",
    callingCode: "1787",
  },
  {
    flag: "qa.png",
    name: "Qatar",
    alpha2Code: "QA",
    callingCode: "974",
  },
  {
    flag: "xk.png",
    name: "Republic of Kosovo",
    alpha2Code: "XK",
    callingCode: "383",
  },
  {
    flag: "re.png",
    name: "Réunion",
    alpha2Code: "RE",
    callingCode: "262",
  },
  {
    flag: "ro.png",
    name: "Romania",
    alpha2Code: "RO",
    callingCode: "40",
  },
  {
    flag: "ru.png",
    name: "Russian Federation",
    alpha2Code: "RU",
    callingCode: "7",
  },
  {
    flag: "rw.png",
    name: "Rwanda",
    alpha2Code: "RW",
    callingCode: "250",
  },
  {
    flag: "bl.png",
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    callingCode: "590",
  },
  {
    flag: "sh.png",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    callingCode: "290",
  },
  {
    flag: "kn.png",
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    callingCode: "1869",
  },
  {
    flag: "lc.png",
    name: "Saint Lucia",
    alpha2Code: "LC",
    callingCode: "1758",
  },
  {
    flag: "mf.png",
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    callingCode: "590",
  },
  {
    flag: "pm.png",
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    callingCode: "508",
  },
  {
    flag: "vc.png",
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    callingCode: "1784",
  },
  {
    flag: "ws.png",
    name: "Samoa",
    alpha2Code: "WS",
    callingCode: "685",
  },
  {
    flag: "sm.png",
    name: "San Marino",
    alpha2Code: "SM",
    callingCode: "378",
  },
  {
    flag: "st.png",
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    callingCode: "239",
  },
  {
    flag: "sa.png",
    name: "Saudi Arabia",
    alpha2Code: "SA",
    callingCode: "966",
  },
  {
    flag: "sn.png",
    name: "Senegal",
    alpha2Code: "SN",
    callingCode: "221",
  },
  {
    flag: "rs.png",
    name: "Serbia",
    alpha2Code: "RS",
    callingCode: "381",
  },
  {
    flag: "sc.png",
    name: "Seychelles",
    alpha2Code: "SC",
    callingCode: "248",
  },
  {
    flag: "sl.png",
    name: "Sierra Leone",
    alpha2Code: "SL",
    callingCode: "232",
  },
  {
    flag: "sg.png",
    name: "Singapore",
    alpha2Code: "SG",
    callingCode: "65",
  },
  {
    flag: "sx.png",
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    callingCode: "1721",
  },
  {
    flag: "sk.png",
    name: "Slovakia",
    alpha2Code: "SK",
    callingCode: "421",
  },
  {
    flag: "si.png",
    name: "Slovenia",
    alpha2Code: "SI",
    callingCode: "386",
  },
  {
    flag: "sb.png",
    name: "Solomon Islands",
    alpha2Code: "SB",
    callingCode: "677",
  },
  {
    flag: "so.png",
    name: "Somalia",
    alpha2Code: "SO",
    callingCode: "252",
  },
  {
    flag: "za.png",
    name: "South Africa",
    alpha2Code: "ZA",
    callingCode: "27",
  },
  {
    flag: "gs.png",
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    callingCode: "500",
  },
  {
    flag: "kr.png",
    name: "Korea (Republic of)",
    alpha2Code: "KR",
    callingCode: "82",
  },
  {
    flag: "ss.png",
    name: "South Sudan",
    alpha2Code: "SS",
    callingCode: "211",
  },
  {
    flag: "es.png",
    name: "Spain",
    alpha2Code: "ES",
    callingCode: "34",
  },
  {
    flag: "lk.png",
    name: "Sri Lanka",
    alpha2Code: "LK",
    callingCode: "94",
  },
  {
    flag: "sd.png",
    name: "Sudan",
    alpha2Code: "SD",
    callingCode: "249",
  },
  {
    flag: "sr.png",
    name: "Suriname",
    alpha2Code: "SR",
    callingCode: "597",
  },
  {
    flag: "sj.png",
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    callingCode: "4779",
  },
  {
    flag: "sz.png",
    name: "Swaziland",
    alpha2Code: "SZ",
    callingCode: "268",
  },
  {
    flag: "se.png",
    name: "Sweden",
    alpha2Code: "SE",
    callingCode: "46",
  },
  {
    flag: "ch.png",
    name: "Switzerland",
    alpha2Code: "CH",
    callingCode: "41",
  },
  {
    flag: "sy.png",
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    callingCode: "963",
  },
  {
    flag: "tw.png",
    name: "Taiwan",
    alpha2Code: "TW",
    callingCode: "886",
  },
  {
    flag: "tj.png",
    name: "Tajikistan",
    alpha2Code: "TJ",
    callingCode: "992",
  },
  {
    flag: "tz.png",
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    callingCode: "255",
  },
  {
    flag: "th.png",
    name: "Thailand",
    alpha2Code: "TH",
    callingCode: "66",
  },
  {
    flag: "tl.png",
    name: "Timor-Leste",
    alpha2Code: "TL",
    callingCode: "670",
  },
  {
    flag: "tg.png",
    name: "Togo",
    alpha2Code: "TG",
    callingCode: "228",
  },
  {
    flag: "tk.png",
    name: "Tokelau",
    alpha2Code: "TK",
    callingCode: "690",
  },
  {
    flag: "to.png",
    name: "Tonga",
    alpha2Code: "TO",
    callingCode: "676",
  },
  {
    flag: "tt.png",
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    callingCode: "1868",
  },
  {
    flag: "tn.png",
    name: "Tunisia",
    alpha2Code: "TN",
    callingCode: "216",
  },
  {
    flag: "tr.png",
    name: "Turkey",
    alpha2Code: "TR",
    callingCode: "90",
  },
  {
    flag: "tm.png",
    name: "Turkmenistan",
    alpha2Code: "TM",
    callingCode: "993",
  },
  {
    flag: "tc.png",
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    callingCode: "1649",
  },
  {
    flag: "tv.png",
    name: "Tuvalu",
    alpha2Code: "TV",
    callingCode: "688",
  },
  {
    flag: "ug.png",
    name: "Uganda",
    alpha2Code: "UG",
    callingCode: "256",
  },
  {
    flag: "ua.png",
    name: "Ukraine",
    alpha2Code: "UA",
    callingCode: "380",
  },
  {
    flag: "ae.png",
    name: "United Arab Emirates",
    alpha2Code: "AE",
    callingCode: "971",
  },
  {
    flag: "gb.png",
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    callingCode: "44",
  },
  {
    flag: "us.png",
    name: "United States of America",
    alpha2Code: "US",
    callingCode: "1",
  },
  {
    flag: "uy.png",
    name: "Uruguay",
    alpha2Code: "UY",
    callingCode: "598",
  },
  {
    flag: "uz.png",
    name: "Uzbekistan",
    alpha2Code: "UZ",
    callingCode: "998",
  },
  {
    flag: "vu.png",
    name: "Vanuatu",
    alpha2Code: "VU",
    callingCode: "678",
  },
  {
    flag: "ve.png",
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    callingCode: "58",
  },
  {
    flag: "vn.png",
    name: "Viet Nam",
    alpha2Code: "VN",
    callingCode: "84",
  },
  {
    flag: "wf.png",
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    callingCode: "681",
  },
  {
    flag: "eh.png",
    name: "Western Sahara",
    alpha2Code: "EH",
    callingCode: "212",
  },
  {
    flag: "ye.png",
    name: "Yemen",
    alpha2Code: "YE",
    callingCode: "967",
  },
  {
    flag: "zm.png",
    name: "Zambia",
    alpha2Code: "ZM",
    callingCode: "260",
  },
  {
    flag: "zw.png",
    name: "Zimbabwe",
    alpha2Code: "ZW",
    callingCode: "263",
  },
];

export default countries;
